# Generated by Django 5.2.5 on 2025-09-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_s_nome_autor_s_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ano_publicacao',
            new_name='ano',
        ),
    ]
